language: node_js
node_js:
  - "node"
  - "10"

cache: yarn
install: yarn

script: yarn export

deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: "precious-snowflake"