language: node_js
node_js:
  - "node"
  - "10"

cache: yarn
install: yarn

script: yarn export

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"